= link:https://www.zhleatherworks.cz/waste_calendar/[Svoz odpadu v Lysé nad Labem a místních částech]

== Proč vznikl web link:https://www.zhleatherworks.cz/waste_calendar/[www.zhleatherworks.cz/waste_calendar/]
* *Absence městského řešení* +
Ve městě se rozbíhá nový systém třídění odpadu. S přibývajícími popelnicemi u rodinných domů přibývá také
svozových dnů v kalendáři. Jelikož město nemělo vlastní řešení pro automatizované publikování kalendáře online
adaptoval jsem již funkční https://github.com/honza-kasik/svoz_odpadu_litovel[řešení Honzy Kašíka], které vytvořil pro město Litovel.

* *Rychlost kdekoliv* +
Vše je minimalistické a velmi rychlé na jekémkoliv zařízení a připojení

* *Přesné informace podle adresy* +
Vybereš ulici, dostaneš kalendář.

* *Reflektuje změny ve svozu* +
Pokud město změní harmonogram (svátky, výluky), kalednář je upraven.

* *Jednoduchost bez zbytečností* +
Nechceš přemýšlet, jestli je zrovna sudý nebo lichý týden.

== Obsah repozitáře

Velmi jednoduchý a naivní skript pro vygenerování `ics` souborů a `csv` souboru se svozy odpadů pro jednotlivé ulice i místní části.

Soubor `ics` lze importovat do Google kalendáře a pravděpodobně i dalších aplikací. Kalendáře jsou ke stažení ve složce link:calendars/[`calendars`].

Soubor `csv` slouží primárně jako zdroj dat pro link:index.html[index.html] dostupný z https://www.zhleatherworks.cz/waste_calendar/

== Import ics do Google kalendáře

=== Včetně synchronizace a notifikace v mobilu

link:docs/synchronizace-notifikace.adoc[Synchronizace/notifikace pro svozy odpadů]

=== Bez synchronizace

https://support.google.com/calendar/answer/37118?hl=cs&co=GENIE.Platform%3DDesktop

== Zdrojová data

Zdrojová data se nachází v link:resources/[resources/]. Jsou to informace z webu nebo materiálů města Lysá nad Labem. Součástí repozitáře jsou proto, aby byly dohledatelné případné změny.

=== Změny svozu

* 2025-09-29 úvodní verze pro Lysou nad Labem

== Licence

The GNU General Public License v3.0 dostupná na https://www.gnu.org/licenses/gpl-3.0.en.html
