"""
Pevne lokace, ktere by se nemely menit, zadna logika krome "zbytku mesta".
"""

all_streets = {
    'Lysa': [
        '28. října',
        '9. května',
        'Alešova',
        'Blahoslavova', 
        'Boženy Němcové',
        'Brandlova',
        'Braunova',
        'Brigádnická',
        'Brožíkova',
        'Byšičky',
        'Čapkova',
        'Čechova',
        'Čelakovského',
        'Československé armády',
        'Cihelna',
        'Dobrovského sady',
        'Dohalského',
        'Dolejší',
        'Družstevní',
        'Dukelská',
        'Dvořákova',
        'Dvorce',
        'Dvorecká',
        'Fibichova',
        'Fuksova',
        'Gen. Přikryla',
        'Havlíčkovo náměstí',
        'Havlínova',
        'Hořejší',
        'Hrabanov',
        'Husova',
        'Husovo náměstí',
        'Jahodová',
        'Janulova',
        'Jaromírovy sady',
        'Járy Cimrmana',
        'Jedličkova',
        'Jiráskova',
        'Kafkova',
        'Kaprova',
        'Karlov',
        'K bažantnici',
        'K Borku',
        'Ke Karlovu',
        'Ke Kovoně',
        'Ke Skále',
        'Ke Střelnici',
        'Ke Vrutici',
        'Klicperova',
        'K Milovicům',
        'Kollárova',
        'Komenského',
        'Kpt. Jaroše',
        'Králíčkova',
        'Krátká',
        'Křižíkova',
        'K Šibáku',
        'Kupkova',
        'K Závodišti (křížení Ke Karlovu)',
        'Legionářská',
        'Lidická',
        'Lipová',
        'Lom',
        'Luční',
        'Máchova',
        'Mánesova',
        'Masarykova',
        'Mírová',
        'Mladá',
        'Muchova',
        'Na Brůdku',
        'Na Homolce',
        'Náměstí B. Hrozného',
        'Na Mlíčníku',
        'Na Písku',
        'Na Rybníčku',
        'Na Staré vsi',
        'Na Vlečce',
        'Na Výsluní',
        'Na Vysoké mezi',
        'Na Zemské stezce',
        'Nerudova',
        'Nová',
        'Okrsek',
        'Okružní',
        'Olbrachtova',
        'Palackého',
        'Pivovarská',
        'Poděbradova',
        'Pod Klášterem',
        'Přemyslova',
        'Příčná',
        'Průmyslová',
        'Raisova',
        'Řehačka',
        'Resslova',
        'Riegrova',
        'Růžová',
        'Rybízová',
        'Sadová',
        'Šafaříkova',
        'Seifertova',
        'Sídliště',
        'Šípková',
        'Školní náměstí',
        'Škrétova',
        'Škroupova',
        'Skupova',
        'Slunéčkova',
        'Šmeralova',
        'Smetanova',
        'Sojovická',
        'Sokolovská',
        'Sokolská',
        'Spojovací',
        'Šporkova',
        'Stržiště',
        'Švermova',
        'Třebízského',
        'Třešňová',
        'Tylova',
        'Tyršova',
        'U Braňky',
        'U Cihelny',
        'U Dráhy',
        'U křížku',
        'U Nadjezdu',
        'U Nové hospody',
        'U Okrouhlíku',
        'U Stadionu',
        'U Vodárny',
        'Veleslavínova',
        'Ve Skále',
        'Ve Vilách',
        'Ve Višňovce',
        'Vichrova',
        'Vojáčkova',
        'Vojanova',
        'V Olších',
        'V Polích',
        'Vrchlického',
        'V Zátiší',
        'Zahradní',
        'Za Koncem',
        'Za Kruhovkou',
        'Za Labem',
        'Zámecká',
        'Zámek',
        'Za Pávem'
        'Za Zámkem',
        'Žižkova'
    ]
}

oblasti = {
    'Oblast A': [
        'Dvorce',
        'Byšičky',
        'Řehačka',
        'Litol',


    ]

}
oblasti['Oblast B'] = [street for street in all_streets['Lysa'] if street not in oblasti['Oblast A']]


mistni_casti = ['Litol', 'Byšičky', 'Karlov', 'Dvorce', 'Řehačka']

#jednotlive lokace, ktere se svazi ve stejny den
#svoz plastu
lysa_lokace_plast_0 = oblasti['Oblast A']
lysa_lokace_plast_1 = oblasti['Oblast B']

#svoz papiru
lysa_lokace_papir_0 = oblasti['Oblast A']
lysa_lokace_papir_1 = oblasti['Oblast B']

#svoz bio
lysa_lokace_bio_0 = oblasti['Oblast A']
lysa_lokace_bio_1 = oblasti['Oblast B']

#svoz smesneho odpadu, cislo v nazvu je poradi v jakem je mnozina lokaci v letacku
#sude utery
lysa_lokace_smes_0 = [
    'Alešova',
    'Blahoslavova', 
    'Brandlova',
    'Braunova',
    'Cihelna',
    'Čapkova',
    'Čechova',
    'Čelakovského',
    'Dvorecká',
    'Dvořákova',
    'Fibichova',
    'Havlíčkovo náměstí',
    'Hrabanov',
    'Janulova',
    'Jaromírovy sady',
    'K bažantnici',
    'Kaprova',
    'Ke Karlovu',
    'Ke Kovoně',
    'Ke Skále',
    'Ke Střelnici',
    'Kpt. Jaroše',
    'Kupkova',
    'Lom',
    'Máchova',
    'Masarykova',
    'Muchova',
    'Na Rybníčku',
    'Náměstí B. Hrozného',
    'Pod Klášterem',
    'Příčná',
    'Raisova',
    'Riegrova',
    'Sadová',
    'Sojovická',
    'Stržiště',
    'Šporkova',
    'Tyršova',
    'U Braňky',
    'U Cihelny',
    'U křížku',
    'V Olších',
    'V Polích',
    'Ve Skále',
    'Vojanova',
    'Za Zámkem',
    'Zámecká',
    'Zámek',
    'Žižkova'
]
#suda streda
lysa_lokace_smes_1 = [
    'Byšičky',
    'Řehačka',
    'Dvorce',
    'Brigádnická',
    'Karlov',
    'Klicperova',
    'Lipová',
    'Mladá',
    'Na Mlíčníku',
    'Okrsek',
    'Poděbradova',
    'Průmyslová',
    'Růžová',
    'Skupova',
    'Tylova',
    'U Okrouhlíku',
    'V Zátiší',
    'Za Koncem'
]
#sudy ctvrtek
lysa_lokace_smes_2 = [
    '28. října',
    '9. května',
    'Boženy Němcové',
    'Brožíkova',
    'Československé armády',
    'Dobrovského sady',
    'Dohalského',
    'Dolejší',
    'Družstevní',
    'Dukelská',
    'Fuksova',
    'Gen. Přikryla',
    'Havlínova',
    'Hořejší',
    'Husova',
    'Husovo náměstí',
    'Jahodová',
    'Járy Cimrmana',
    'Jedličkova',
    'Jiráskova',
    'K Borku',
    'K Šibáku',
    'K Závodišti (křížení Ke Karlovu)',
    'Kafkova',
    'Ke Vrutici',
    'Kollárova',
    'Komenského',
    'Králíčkova',
    'Krátká',
    'Křižíkova',
    'Legionářská',
    'Lidická',
    'Litol',
    'Mánesova',
    'Mírová',
    'Na Brůdku',
    'Na Písku',
    'Na Staré vsi',
    'Na Vlečce',
    'Na Vysoké mezi',
    'Na Zemské stezce',
    'Nerudova',
    'Nová',
    'Olbrachtova',
    'Palackého',
    'Pivovarská',
    'Přemyslova',
    'Resslova',
    'Rybízová',
    'Seifertova',
    'Slunéčkova',
    'Smetanova',
    'Sokolovská',
    'Sokolská',
    'Spojovací',
    'Šafaříkova',
    'Šípková',
    'Školní náměstí',
    'Škrétova',
    'Škroupova',
    'Šmeralova',
    'Švermova',
    'Třebízského',
    'Třešňová',
    'U Dráhy',
    'U Nadjezdu',
    'U Nové hospody',
    'U Stadionu',
    'Ve Vilách',
    'Ve Višňovce',
    'Veleslavínova',
    'Vichrova',
    'Vojáčkova',
    'Vrchlického',
    'Za Kruhovkou',
    'Za Labem',
    'Zahradní'
]

lysa_lokace_smes_3 = [
    'K Milovicům',
    'Luční',
    'Na Homolce',
    'Okružní',
    'Sídliště',
    'U Vodárny',
    'Za Pávem'
]

